### ISSUE TITLE
Schedule does not start on month for current day

### ISSUE THREAD

**Issue by dport96** [morea-framework/morea#13]
In migrating to V3 I noticed that the Schedule calendar does not automatically start on the month for the current day. If you press the today button it will set the calendar to the  month for the current day. 

I have not looked into weather this is a feature, bug, or incompatibility between MOREA V2 and V3 schedules (my guess is the latter). I'm not sure if I copied the V2 schedule templates when I migrated to V3.

**Comment by philipmjohnson** [comment]
That is a really cool idea, and I started to implement it the way you suggested, only to realize that the schedule/index.html page contains other data that must be configured (i.e. holidays and their colors), and it ultimately seems easier to simply edit that file directly rather than push all of that configuration up to the `_config.yml`.

So, instead, I have made a change to the Instructor Guide to call out the need to configure the schedule page as part of the getting started process:

http://morea-framework.github.io/docs/instructors/local-development#continuing-on

Thanks for your thoughtful comment and suggestion!
